name: huldra
description: A deranged discord bot.
version: 0.9.12

environment:
  sdk: "^3.7.0"

dependencies:
  crypto: ^3.0.1
  drift: ^2.3.0
  injector: ^4.0.0
  nyxx: ^6.6.0
  nyxx_extensions: ^4.3.0
  path: ^1.8.0
  sqlite3: ^2.7.5
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^2.3.2
  pedantic: ^1.11.0
  test: ^1.17.4
