name: huldra
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  crypto: ^2.1.4
  hive: ^1.4.4+1
  injector: ^1.0.8
  json_serializable: ^3.5.0
  moor: ^3.4.0
  nyxx: ^0.30.0
  path: ^1.6.0
  sqlite3: ^0.1.7
  yaml_config: ^0.1.2

dev_dependencies:
  build_runner: ^1.10.4
  hive_generator: ^0.8.1
  moor_generator: ^3.4.0
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  nyxx:
    git:
      url: https://github.com/l7ssha/nyxx.git
      ref: development
